### ISSUE TITLE
No live link

### ISSUE THREAD

**Issue by d-a-ve** [igudy/DriveDreamscape-CarShowcase#1]
Boss I dey see your work, abeg dey add live link after you deploy so your fans go fit see wetin you cook properly.

Thanks chief.

**Comment by igudy** [comment]
😂😂😂. I will add it as soon as i'm done. Thank you boss.

**Comment by d-a-ve** [comment]
> 😂😂😂. I will add it as soon as i'm done. Thank you boss.

Alright boss, I go dey wait.

**Comment by igudy** [comment]
I later didn't finish this project😂. This tech too funny guyyy

**Comment by d-a-ve** [comment]
> I later didn't finish this project😂. This tech too funny guyyy

I thought you finished it since I was seeing some commits.

This tech funny ngl😂😂
